{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b6a90680",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.stats import boxcox\n",
    "\n",
    "from sklearn.model_selection import train_test_split, GridSearchCV\n",
    "from sklearn.preprocessing import OneHotEncoder, StandardScaler\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.pipeline import Pipeline\n",
    "\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.tree import DecisionTreeRegressor\n",
    "from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor\n",
    "from sklearn.svm import SVR\n",
    "from sklearn.neighbors import KNeighborsRegressor\n",
    "from xgboost import XGBRegressor\n",
    "\n",
    "from catboost import CatBoostRegressor\n",
    "from lightgbm import LGBMRegressor\n",
    "\n",
    "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "df = pd.read_csv(\"House Price.csv\")\n",
    "\n",
    "print(df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ab8fd355",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(df.info())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1d37860a",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(df.describe().T)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7208237a",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(df.isnull().sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "008156fe",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(df.duplicated().sum())\n",
    "df.drop_duplicates(inplace=True)\n",
    "print(df.duplicated().sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "510da8c7",
   "metadata": {},
   "outputs": [],
   "source": [
    "df['POSTED_BY'] = df['POSTED_BY'].map({'Owner': 0, 'Dealer': 1, 'Builder': 2})\n",
    "\n",
    "df['BHK_OR_RK'] = df['BHK_OR_RK'].map({'BHK': 0, 'RK': 1})\n",
    "\n",
    "\n",
    "if 'ADDRESS' in df.columns:\n",
    "    df.drop(['ADDRESS'], axis=1, inplace=True)\n",
    "    \n",
    "num_cols = ['POSTED_BY','UNDER_CONSTRUCTION','RERA','BHK_NO.','BHK_OR_RK','SQUARE_FT',\n",
    "            'READY_TO_MOVE','RESALE','LONGITUDE','LATITUDE',\n",
    "            'TARGET(PRICE_IN_LACS)']\n",
    "\n",
    "for col in num_cols:\n",
    "    plt.figure(figsize=(6,4))\n",
    "    sns.histplot(df[col], kde=True)\n",
    "    plt.title(f\"Distribution of {col}\")\n",
    "    plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "413c8a75",
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(10,8))\n",
    "sns.heatmap(df[num_cols].corr(), annot=True, cmap=\"coolwarm\")\n",
    "plt.title(\"Correlation Heatmap\")\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "90dc85c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\"\"\" print (df[num_cols].skew())\n",
    "# Columns to skip from skewness check\n",
    "skip_cols = [\"LONGITUDE\", \"LATITUDE\", \"UNDER_CONSTRUCTION\", \"READY_TO_MOVE\", \"RESALE\", \"BHK_OR_RK\"]\n",
    "\n",
    "# Compute skewness\n",
    "skew_vals = df[num_cols].skew().abs()\n",
    "\n",
    "# Filter skewed columns while skipping unwanted ones\n",
    "skewed_cols = [col for col in skew_vals.index if skew_vals[col] > 1 and col not in skip_cols]\n",
    "\n",
    "df[skewed_cols] = np.log1p(df[skewed_cols])  \n",
    "print(\"Skewed columns:\", skewed_cols)\n",
    "print(df[skewed_cols].skew()) \"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b0bd0d17",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(df[num_cols].skew())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "24a74518",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(df.isna().sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "400b245d",
   "metadata": {},
   "outputs": [],
   "source": [
    "for col in num_cols:\n",
    "    plt.figure(figsize=(6,4))\n",
    "    sns.boxplot(x=df[col], color=\"lightgreen\")\n",
    "    plt.title(f\"Boxplot – {col}\")\n",
    "    plt.xlabel(col)\n",
    "    plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "46f3928d",
   "metadata": {},
   "outputs": [],
   "source": [
    "col = \"TARGET(PRICE_IN_LACS)\"\n",
    "\n",
    "Q1 = df[col].quantile(0.25)\n",
    "Q3 = df[col].quantile(0.75)\n",
    "IQR = Q3 - Q1\n",
    "lower = Q1 - 1.5 * IQR\n",
    "upper = Q3 + 1.5 * IQR\n",
    "\n",
    "plt.figure(figsize=(7,4))\n",
    "sns.boxplot(x=df[col], color=\"orange\")\n",
    "\n",
    "plt.axvline(lower, color='red', linestyle='--', label='Lower Bound')\n",
    "plt.axvline(upper, color='blue', linestyle='--', label='Upper Bound')\n",
    "\n",
    "plt.title(f\"Boxplot with Outlier Bounds – {col}\")\n",
    "plt.legend()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9bf3bfb2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7c4e5cdd",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "def remove_outliers(df, col):\n",
    "    Q1 = df[col].quantile(0.25)\n",
    "    Q3 = df[col].quantile(0.75)\n",
    "    IQR = Q3 - Q1\n",
    "    lower = Q1 - 1.5*IQR\n",
    "    upper = Q3 + 1.5*IQR\n",
    "    return df[(df[col] >= lower) & (df[col] <= upper)]\n",
    "for col in num_cols:\n",
    "    df = remove_outliers(df, col)\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9818e7d",
   "metadata": {},
   "outputs": [],
   "source": [
    "target = \"TARGET(PRICE_IN_LACS)\"\n",
    "X = df.drop(columns=[target])\n",
    "y = df[target]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9cfb3664",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=42\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a987d4b6",
   "metadata": {},
   "outputs": [],
   "source": [
    "Scaler=StandardScaler()\n",
    "X_Train_Scaled=Scaler.fit_transform(X_train)\n",
    "X_Test_Scaled=Scaler.transform(X_test)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e0a85729",
   "metadata": {},
   "outputs": [],
   "source": [
    "models = {\n",
    "    \"Linear Regression\": LinearRegression(),\n",
    "    \"Decision Tree\": DecisionTreeRegressor(random_state=42),\n",
    "    \"Random Forest\": RandomForestRegressor(random_state=42),\n",
    "    \"SVR\": SVR(),\n",
    "    \"KNN\": KNeighborsRegressor(),\n",
    "    \"Gradient Boosting\": GradientBoostingRegressor(random_state=42),\n",
    "    \"XGBoost\": XGBRegressor(random_state=42),\n",
    "    \"CatBoost\": CatBoostRegressor(random_state=42),\n",
    "    \"LightGBM\": LGBMRegressor(random_state=42)\n",
    "}\n",
    "\n",
    "results = []\n",
    "\n",
    "def metrics(y_true, y_pred):\n",
    "    mae = mean_absolute_error(y_true, y_pred)\n",
    "    mse = mean_squared_error(y_true, y_pred)\n",
    "    rmse = np.sqrt(mse)\n",
    "    r2 = r2_score(y_true, y_pred)\n",
    "    return mae, mse, rmse, r2\n",
    "\n",
    "\n",
    "for name, model in models.items():\n",
    "    # Handle NaN values by filling with mean\n",
    "    X_train_filled = np.nan_to_num(X_Train_Scaled, nan=np.nanmean(X_Train_Scaled))\n",
    "    X_test_filled = np.nan_to_num(X_Test_Scaled, nan=np.nanmean(X_Train_Scaled))\n",
    "    \n",
    "    model.fit(X_train_filled, y_train)\n",
    "    \n",
    "    \n",
    "    y_train_pred = model.predict(X_Train_Scaled)\n",
    "    y_test_pred = model.predict(X_Test_Scaled)\n",
    "    \n",
    "    mae_tr, mse_tr, rmse_tr, r2_tr = metrics(y_train, y_train_pred)\n",
    "    mae_te, mse_te, rmse_te, r2_te = metrics(y_test, y_test_pred)\n",
    "    \n",
    "    results.append([name, rmse_tr, rmse_te, r2_tr, r2_te,\n",
    "                    \"Y\" if (r2_tr - r2_te) > 0.05 else \"N\"])\n",
    "\n",
    "results_df = pd.DataFrame(results, columns=[\n",
    "    \"Model\",\"Train RMSE\",\"Test RMSE\",\"Train R2\",\"Test R2\",\"Overfitting\"\n",
    "])\n",
    "\n",
    "results_df_sorted = results_df.sort_values(\n",
    "    by=[\"Test R2\", \"Test RMSE\"],\n",
    "    ascending=[False, False]\n",
    ")\n",
    "\n",
    "print(results_df_sorted)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9f6a7eb7",
   "metadata": {},
   "outputs": [],
   "source": [
    "dt = DecisionTreeRegressor(\n",
    "    max_depth=5,\n",
    "    min_samples_split=20,\n",
    "    min_samples_leaf=10,\n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "\n",
    "param_grid_dt = {\n",
    "    'max_depth': [3, 5, 7, 10],\n",
    "    'min_samples_split': [5, 10, 20, 30],\n",
    "    'min_samples_leaf': [2, 5, 10, 15],\n",
    "    'max_features': ['sqrt', 'log2', None]\n",
    "}\n",
    "\n",
    "grid_dt = GridSearchCV(\n",
    "    \n",
    "    dt,\n",
    "    param_grid_dt,\n",
    "    cv=5,\n",
    "    scoring='r2',\n",
    "    n_jobs=-1,\n",
    "    verbose=1\n",
    ")\n",
    "grid_dt.fit(X_Train_Scaled, y_train)\n",
    "best_dt = grid_dt.best_estimator_\n",
    "\n",
    "y_train_pred_best_dt = best_dt.predict(X_Train_Scaled)\n",
    "y_test_pred_best_dt = best_dt.predict(X_Test_Scaled)\n",
    "\n",
    "mae_tr, mse_tr, rmse_tr, r2_tr = metrics(y_train, y_train_pred_best_dt)\n",
    "mae_te, mse_te, rmse_te, r2_te = metrics(y_test, y_test_pred_best_dt)\n",
    "\n",
    "results.append([\"Decision Tree Tuned\", rmse_tr, rmse_te, r2_tr, r2_te,\"Y\" if (r2_tr - r2_te) > 0.05 else \"N\"])\n",
    "\n",
    "results_df = pd.DataFrame(results, columns=[\n",
    "    \"Model\",\"Train RMSE\",\"Test RMSE\",\"Train R2\",\"Test R2\",\"Overfitting\"\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "22cea5a2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Random Forest tuning\n",
    "rf = RandomForestRegressor(random_state=42)\n",
    "\n",
    "param_grid_rf  = {\n",
    "    \"n_estimators\": [500, 700],\n",
    "    \"max_depth\": [20, 30, None],\n",
    "    \"min_samples_split\": [2, 3],\n",
    "    \"min_samples_leaf\": [1, 2, 3],\n",
    "    \"max_features\": [\"log2\"]\n",
    "}\n",
    "\n",
    "grid_rf = GridSearchCV(\n",
    "    rf, param_grid_rf, cv=2, scoring='r2', n_jobs=-1, verbose=1\n",
    ")\n",
    "grid_rf.fit(X_Train_Scaled, y_train)\n",
    "\n",
    "print(\"Best RF params:\", grid_rf.best_params_)\n",
    "print(\"Best RF CV score:\", grid_rf.best_score_)\n",
    "\n",
    "best_rf = grid_rf.best_estimator_\n",
    "y_train_pred_best_rf = best_rf.predict(X_Train_Scaled)\n",
    "y_test_pred_best_rf = best_rf.predict(X_Test_Scaled)\n",
    "    \n",
    "mae_tr, mse_tr, rmse_tr, r2_tr = metrics(y_train, y_train_pred_best_rf)\n",
    "mae_te, mse_te, rmse_te, r2_te = metrics(y_test, y_test_pred_best_rf)\n",
    "\n",
    "results.append([\"Random Forest Tuned1\", rmse_tr, rmse_te, r2_tr, r2_te,\n",
    "                \"Y\" if (r2_tr - r2_te) > 0.05 else \"N\"])\n",
    "results_df = pd.DataFrame(results, columns=[\n",
    "    \"Model\",\"Train RMSE\",\"Test RMSE\",\"Train R2\",\"Test R2\",\"Overfitting\"\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c053bfd6",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "results_df_sorted = results_df.sort_values(\n",
    "    by=[\"Test R2\", \"Test RMSE\"],\n",
    "    ascending=[False, False]\n",
    ")\n",
    "\n",
    "print(results_df_sorted)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0f87cfaa",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d3e35434",
   "metadata": {},
   "outputs": [],
   "source": [
    "#KNN tuning\n",
    "knn = KNeighborsRegressor()\n",
    "\n",
    "param_grid_knn = {\n",
    "    'n_neighbors': [5, 7, 9, 11, 15, 21, 25, 31],\n",
    "    'weights': ['uniform'],\n",
    "    'metric': ['euclidean', 'manhattan', 'minkowski'],\n",
    "    'p': [1, 2]\n",
    "}\n",
    "\n",
    "grid_knn = GridSearchCV(\n",
    "    knn, param_grid_knn, cv=5, scoring='r2', n_jobs=-1, verbose=1\n",
    ")\n",
    "grid_knn.fit(X_Train_Scaled, y_train)\n",
    "best_knn = grid_knn.best_estimator_\n",
    "y_train_pred_best_knn = best_knn.predict(X_Train_Scaled)\n",
    "y_test_pred_best_knn = best_knn.predict(X_Test_Scaled)\n",
    "\n",
    "mae_tr, mse_tr, rmse_tr, r2_tr = metrics(y_train, y_train_pred_best_knn)\n",
    "mae_te, mse_te, rmse_te, r2_te = metrics(y_test, y_test_pred_best_knn)\n",
    "\n",
    "results.append([\"KNN Tuned\", rmse_tr, rmse_te, r2_tr, r2_te,\n",
    "                \"Y\" if (r2_tr - r2_te) > 0.05 else \"N\"])\n",
    "results_df = pd.DataFrame(results, columns=[\n",
    "    \"Model\",\"Train RMSE\",\"Test RMSE\",\"Train R2\",\"Test R2\",\"Overfitting\"\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "acf14678",
   "metadata": {},
   "outputs": [],
   "source": [
    "gd = GradientBoostingRegressor(random_state=42)\n",
    "param_grid_gd = {\n",
    "    \"n_estimators\": [100, 200, 300],    \n",
    "    \"learning_rate\": [0.1, 0.05, 0.01]\n",
    "}\n",
    "grid_gd = GridSearchCV(\n",
    "    gd, param_grid_gd, cv=5, scoring='r2', n_jobs=-1, verbose=1\n",
    ")\n",
    "grid_gd.fit(X_Train_Scaled, y_train)\n",
    "best_gd = grid_gd.best_estimator_\n",
    "y_train_pred_best_gd = best_gd.predict(X_Train_Scaled)\n",
    "y_test_pred_best_gd = best_gd.predict(X_Test_Scaled)\n",
    "\n",
    "mae_tr, mse_tr, rmse_tr, r2_tr = metrics(y_train, y_train_pred_best_gd)\n",
    "mae_te, mse_te, rmse_te, r2_te = metrics(y_test, y_test_pred_best_gd)\n",
    "\n",
    "results.append([\"Gradient Boosting Tuned\", rmse_tr, rmse_te, r2_tr, r2_te,\n",
    "                \"Y\" if (r2_tr - r2_te) > 0.05 else \"N\"])\n",
    "results_df = pd.DataFrame(results, columns=[\n",
    "    \"Model\",\"Train RMSE\",\"Test RMSE\",\"Train R2\",\"Test R2\",\"Overfitting\"\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "088dc0e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "xgb = XGBRegressor(\n",
    "    n_estimators=500,\n",
    "    learning_rate=0.05,\n",
    "    max_depth=6,\n",
    "    subsample=0.8,\n",
    "    colsample_bytree=0.8,\n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "\n",
    "xgb.fit(X_Train_Scaled, y_train)\n",
    "y_train_pred_best_rf = xgb.predict(X_Train_Scaled)\n",
    "y_test_pred_best_rf = xgb.predict(X_Test_Scaled)\n",
    "    \n",
    "mae_tr, mse_tr, rmse_tr, r2_tr = metrics(y_train, y_train_pred_best_rf)\n",
    "mae_te, mse_te, rmse_te, r2_te = metrics(y_test, y_test_pred_best_rf)\n",
    "\n",
    "results.append([\"XGBoost 1\", rmse_tr, rmse_te, r2_tr, r2_te,\n",
    "                \"Y\" if (r2_tr - r2_te) > 0.05 else \"N\"])\n",
    "results_df = pd.DataFrame(results, columns=[\n",
    "    \"Model\",\"Train RMSE\",\"Test RMSE\",\"Train R2\",\"Test R2\",\"Overfitting\"\n",
    "])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea58643f",
   "metadata": {},
   "outputs": [],
   "source": [
    "xgb = XGBRegressor(random_state=42)\n",
    "param_grid_xgb = {\n",
    "    'n_estimators': [500, 1000],\n",
    "    'learning_rate': [0.01],\n",
    "    'max_depth': [6],\n",
    "    'subsample': [0.6, 0.7, 0.8],\n",
    "    'colsample_bytree': [0.6, 0.7, 0.8],\n",
    "    'random_state': [42],\n",
    "    'reg_alpha': [0.1, 0.5, 1, 5],\n",
    "    'reg_lambda': [1, 5, 10, 20]\n",
    "}\n",
    "\n",
    "\n",
    "grid_xgb = GridSearchCV(\n",
    "    xgb, param_grid_xgb, cv=3, scoring='r2', n_jobs=-1, verbose=1\n",
    ")\n",
    "\n",
    "grid_xgb.fit(X_Train_Scaled, y_train)\n",
    "y_train_pred_best_rf = grid_xgb.predict(X_Train_Scaled)\n",
    "y_test_pred_best_rf = grid_xgb.predict(X_Test_Scaled)\n",
    "\n",
    "mae_tr, mse_tr, rmse_tr, r2_tr = metrics(y_train, y_train_pred_best_rf)\n",
    "mae_te, mse_te, rmse_te, r2_te = metrics(y_test, y_test_pred_best_rf)\n",
    "\n",
    "results.append([\"XGBoost Tuned1\", rmse_tr, rmse_te, r2_tr, r2_te,\n",
    "                \"Y\" if (r2_tr - r2_te) > 0.05 else \"N\"])\n",
    "results_df = pd.DataFrame(results, columns=[\n",
    "    \"Model\",\"Train RMSE\",\"Test RMSE\",\"Train R2\",\"Test R2\",\"Overfitting\"\n",
    "])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b3be0cc7",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "cat = CatBoostRegressor(\n",
    "    loss_function='RMSE',\n",
    "    random_state=42,\n",
    "    verbose=0\n",
    ")\n",
    "\n",
    "\n",
    "\n",
    "param_grid = {\n",
    "    'iterations': [1000, 1500],\n",
    "    'learning_rate': [0.03, 0.05],\n",
    "    'depth': [4, 6, 8],\n",
    "    'l2_leaf_reg': [3, 5]\n",
    "}\n",
    "\n",
    "grid_search = GridSearchCV(\n",
    "    estimator=cat,\n",
    "    param_grid=param_grid,\n",
    "    scoring='r2',\n",
    "    cv=2,\n",
    "    n_jobs=-1,\n",
    "    verbose=2\n",
    ")\n",
    "\n",
    "grid_search.fit(X_Train_Scaled, y_train)\n",
    "\n",
    "y_train_pred_best_cboost = grid_search.predict(X_Train_Scaled)\n",
    "y_test_pred_best_cboost = grid_search.predict(X_Test_Scaled)\n",
    "\n",
    "mae_tr, mse_tr, rmse_tr, r2_tr = metrics(y_train, y_train_pred_best_cboost)\n",
    "mae_te, mse_te, rmse_te, r2_te = metrics(y_test, y_test_pred_best_cboost)\n",
    "\n",
    "results.append([\"CatBoost Tuned\", rmse_tr, rmse_te, r2_tr, r2_te,\n",
    "                \"Y\" if (r2_tr - r2_te) > 0.05 else \"N\"])\n",
    "results_df = pd.DataFrame(results, columns=[\n",
    "    \"Model\",\"Train RMSE\",\"Test RMSE\",\"Train R2\",\"Test R2\",\"Overfitting\"\n",
    "])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4b5ba79f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import RandomizedSearchCV\n",
    "\n",
    "\n",
    "lgbm = LGBMRegressor(\n",
    "    objective='regression',\n",
    "    random_state=42,\n",
    "    verbosity=-1\n",
    ")\n",
    "\n",
    "param_grid_lgbm = {\n",
    "    'n_estimators': [500, 1000, 1500, 2000],\n",
    "    'learning_rate': [0.01, 0.03, 0.05, 0.1],\n",
    "    'max_depth': [3, 4, 5, 6, 8, 10],\n",
    "    'num_leaves': [15, 31, 50, 70],\n",
    "    'min_child_samples': [5, 10, 20],\n",
    "    'subsample': [0.6, 0.7, 0.8, 0.9],\n",
    "    'colsample_bytree': [0.6, 0.7, 0.8],\n",
    "    'reg_alpha': [0, 0.1, 0.5],\n",
    "    'reg_lambda': [0, 0.1, 0.5]\n",
    "}\n",
    "\n",
    "random_lgbm = RandomizedSearchCV(\n",
    "    estimator=lgbm,\n",
    "    param_distributions=param_grid_lgbm,\n",
    "    n_iter=15,          \n",
    "    scoring='r2',\n",
    "    cv=3,\n",
    "    random_state=42,\n",
    "    n_jobs=-1,\n",
    "    verbose=1\n",
    ")\n",
    "\n",
    "\n",
    "random_lgbm.fit(X_Train_Scaled, y_train)\n",
    "\n",
    "y_train_pred_best_lgbm = random_lgbm.predict(X_Train_Scaled)\n",
    "y_test_pred_best_lgbm = random_lgbm.predict(X_Test_Scaled)\n",
    "\n",
    "mae_tr, mse_tr, rmse_tr, r2_tr = metrics(y_train, y_train_pred_best_lgbm)\n",
    "mae_te, mse_te, rmse_te, r2_te = metrics(y_test, y_test_pred_best_lgbm)\n",
    "\n",
    "results.append([\"LightGBM Tuned\", rmse_tr, rmse_te, r2_tr, r2_te,\n",
    "                \"Y\" if (r2_tr - r2_te) > 0.05 else \"N\"])\n",
    "results_df = pd.DataFrame(results, columns=[\n",
    "    \"Model\",\"Train RMSE\",\"Test RMSE\",\"Train R2\",\"Test R2\",\"Overfitting\"\n",
    "])\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "58c3ed71",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Model comparison Table:\")\n",
    "\n",
    "results_df_sorted = results_df.sort_values(\n",
    "    by=[\"Test R2\", \"Test RMSE\"],\n",
    "    ascending=[False, False]\n",
    ")\n",
    "\n",
    "print(results_df_sorted)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1c341fd7",
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(10,5))\n",
    "plt.bar(results_df[\"Model\"], results_df[\"Test RMSE\"], color='skyblue')\n",
    "plt.xticks(rotation=45, ha='right')\n",
    "plt.ylabel(\"Test RMSE\")\n",
    "plt.title(\"Model Comparison – Test RMSE\")\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ca91874",
   "metadata": {},
   "outputs": [],
   "source": [
    "models = results_df[\"Model\"]\n",
    "train_rmse = results_df[\"Train RMSE\"]\n",
    "test_rmse = results_df[\"Test RMSE\"]\n",
    "\n",
    "x = np.arange(len(models))\n",
    "width = 0.35\n",
    "\n",
    "plt.figure(figsize=(12,6))\n",
    "plt.bar(x - width/2, train_rmse, width, label='Train RMSE', color='lightgreen')\n",
    "plt.bar(x + width/2, test_rmse, width, label='Test RMSE', color='skyblue')\n",
    "\n",
    "plt.xticks(x, models, rotation=45, ha='right')\n",
    "plt.ylabel(\"RMSE\")\n",
    "plt.title(\"Model Comparison – Train vs Test RMSE\")\n",
    "plt.legend()\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "38e0a054",
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(10,6))\n",
    "plt.barh(results_df[\"Model\"], results_df[\"Test RMSE\"], color='orange')\n",
    "plt.xlabel(\"Test RMSE\")\n",
    "plt.title(\"Model Comparison – Test RMSE (Horizontal)\")\n",
    "plt.gca().invert_yaxis()   # highest model at top\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2461ceea",
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(10,5))\n",
    "plt.bar(results_df[\"Model\"], results_df[\"Test R2\"], color='purple')\n",
    "plt.xticks(rotation=45, ha='right')\n",
    "plt.ylabel(\"Test R² Score\")\n",
    "plt.title(\"Model Comparison – Test R²\")\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ee41cd6f",
   "metadata": {},
   "outputs": [],
   "source": [
    "models = results_df[\"Model\"]\n",
    "train_rmse = results_df[\"Train RMSE\"]\n",
    "test_rmse = results_df[\"Test RMSE\"]\n",
    "train_r2 = results_df[\"Train R2\"]\n",
    "test_r2 = results_df[\"Test R2\"]\n",
    "\n",
    "x = np.arange(len(models))\n",
    "width = 0.35\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(16,6))\n",
    "\n",
    "# ---------------- RMSE subplot ----------------\n",
    "axes[0].bar(x - width/2, train_rmse, width, label='Train RMSE', color='lightgreen')\n",
    "axes[0].bar(x + width/2, test_rmse, width, label='Test RMSE', color='skyblue')\n",
    "\n",
    "axes[0].set_title(\"Model Comparison – RMSE\")\n",
    "axes[0].set_xticks(x)\n",
    "axes[0].set_xticklabels(models, rotation=45, ha='right')\n",
    "axes[0].set_ylabel(\"RMSE\")\n",
    "axes[0].legend()\n",
    "\n",
    "# ---------------- R² subplot ----------------\n",
    "axes[1].bar(x - width/2, train_r2, width, label='Train R²', color='orange')\n",
    "axes[1].bar(x + width/2, test_r2, width, label='Test R²', color='purple')\n",
    "\n",
    "axes[1].set_title(\"Model Comparison – R² Score\")\n",
    "axes[1].set_xticks(x)\n",
    "axes[1].set_xticklabels(models, rotation=45, ha='right')\n",
    "axes[1].set_ylabel(\"R² Score\")\n",
    "axes[1].legend()\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aa375588",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "myenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
